export const helpArticles = [
  {
    question: 'Como vejo o resumo do retiro?',
    answer: 'Abra Início para ver os principais números do retiro em foco, atalhos de acompanhamento e indicadores gerais.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral',
  },
      {
    question: 'Onde encontrar o número de pessoas por dias no retiro?',
    answer: 'Abra Início, vá até a coluna Diversos, lá você encontra Presença por dia. A quantidade exibida jé é a soma da equipe de trabalho, cursistas e crianças no espaço kids inscritos no retiro no momento da consulta.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pessoas participação diária dias',
  },
      {
    question: 'Onde encontrar a relação das cidades com participação no retiro?',
    answer: 'Abra Início, vá até a coluna Diversos, lá você encontra Cidades participantes.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral cidade cidades presença',
  },
    {
    question: 'Onde encontrar os cursistas aniversariantes do mês?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Aniversariantes do mês.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pato formiga aniversariantes',
  },
      {
    question: 'Onde encontrar os cursistas com problemas de saúde?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Possui problemas de saúde.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral saúde',
  },
      {
    question: 'Onde encontrar os relação/resumo das quantidades de camisetas dos cursistas?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Camisetas dos cursistas.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral camisetas camiseta',
  },
      {
    question: 'Como imprimir a relação de tamanhos de camisetas por comunidade?',
    answer: 'Abra Comunidades, vá em Imprimir Nr camisetas por comunidade.',
    target: 'Comunidades',
    keywords: 'camiseta camisetas comunidade separar',
  },
      {
    question: 'Como encontrar os cursistas aniversariantes do mês?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Aniversariantes do mês.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pato formiga aniversariantes',
  },
      {
    question: 'Onde encontrar os cursistas que necessitam de acolhimento?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra  Precisa acolhimento.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral acolhimento',
  },
      {
    question: 'Onde encontrar integrantes da equipe de trabalho  aniversariantes do mês?',
    answer: 'Abra Início, vá até a coluna Equipe de trabalho, lá você encontra Aniversariantes do mês.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pato formiga aniversariantes',
  },
      {
    question: 'Onde encontrar os integrantes da equipe de trabalho que solicitaram quandrante impresso?',
    answer: 'Abra Início, vá até a coluna Equipe de trabalho, lá você encontra a informação Quadrante(s) impresso.',
    target: 'Início',
    keywords: 'quadrante',
  },
      {
    question: 'Como calcular quantos quadrantes deve ser impresso?',
    answer: 'Verifique a quantidade de cursistas ou de casais cursistas e acrescente á quantidade solicitada pela equipe de trabalho.',
    target: 'Início',
    keywords: 'quantidade quadrante',
  },
      {
    question: 'Como imprimir/visualizar o quadrante?',
    answer: 'Abra Quadrante, lá você encontra a opçãso Imprimir relatório completo.',
    target: 'Quadrante',
    keywords: 'quadrante relatório',
  },
        {
    question: 'Como imprimir/visualizar lista para amigo secreto?',
    answer: 'Abra Quadrante, lá você encontra a opção Imprimir relatório para amigo secreto.',
    target: 'Quadrante',
    keywords: 'amigo secreto',
  },
    {
    question: 'Como compartilhar os links de inscrição das equipes de trabalho?',
    answer: 'Abra Links de cadastro e digite no campo Buscar setor ativo qual setor que deseja compartilhar o link. Observe que em cada setor há dois links. CADASTRO que é para cadastro da equipe de trabalho daquele setor especificamente e deve ser encaminhado para quem vai preencher a inscrição. ACOMPANHAMENTO DO LIDER que serve para o coordenador do setor verificar quem já efetuou a inscrição, esse último link fica apenas com o coordenador do setor.',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro equipe trabalho compartilhar enviar setor',
  },
      {
    question: 'Como compartilhar os links de inscrição de fichas de cursistas?',
    answer: 'Abra Links de cadastro, digite no campo Buscar ficha, qual a ficha que deseja compartilhar o link. Abrirá uma lista que será possivel visualizar quais fichas já estão cadastradas. Busque uma ficha que estiver livre e clique nela. Você encontrará o link para compartilhamento daquela ficha especificamente. Opcionalmente você poderá preencher o campo Enviado para que serve como campo de observação ficando registrado para quem foi enviado o link. Lembrando que esse campo de observação só ficará quardado se cliar em Salvar',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cursista compartilhar enviar',
  },
      {
    question: 'Como cancelar links de isncrição de cursistas?',
    answer: 'Abra Links de cadastro e digite no campo Buscar ficha qual link deseja cancelar. Ficará visível a opção INSCRIÇÃO ENCERRADA, clique nela, aguarde alguns segundos e pronto, o link ficará inválido. Obs.: Essa operação poderá ser revertida clicando novamente nessa opção',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cancelar reverter compartilhar enviar',
  },
      {
    question: 'Posso cadastrar pelo sistema uma ficha de cursista de um link que foi compartilhado?',
    answer: 'Pode, porém lembrando que o link compartilhado daquele número de ficha especificamente ficará inválido a partir do salvamento da ficha do cursista',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cancelar reverter compartilhar enviar cursista sistema logado',
  },
      {
    question: 'Como encerrar as inscrições da equipe de trabalho?',
    answer: 'Abra Links de cadastro e digite no campo Buscar setor ativo o setor que deseja, clique no setor e ficará visivel a opção Inscrições encerradas. Obs.: Essa ação pode ser revertida apenas clicando novamente nessa mesma opção.',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cancelar reverter compartilhar enviar equipe trabalho',
  },
  {
    question: 'Como cadastrar alguém da equipe de trabalho?',
    answer: 'Abra Equipe de trabalho para cadastrar, editar ou consultar pessoas e fichas de adesão da equipe do retiro.',
    target: 'Equipe de trabalho',
    keywords: 'equipe trabalho voluntario voluntário pessoa adesao adesão cadastrar editar consultar',
  },
  {
    question: 'Como alterar o setor de um integrante da equipe de trabalho?',
    answer: 'Abra Equipe de trabalho, busque o integrante/casal que deseja alterar o setor, já até o tópico Setor de trabalho. Lá estará setado o setro que foi feito o cadastro pelo link. Basta setar no novo setor e salvar.',
    target: 'Equipe de trabalho',
    keywords: 'equipe trabalho alterar setor setor mudar trocar',
  },
   {
    question: 'Como personalizar o nome de alguém da equipe de trabalho no crachá?',
    answer: 'Abra Equipe de trabalho, busque o nome da pessoa que deseja personalizar o nome no crachá e preencha o campo Nome para crachá. A partir deste momento, na impressão do crachá ele vei ignorar o primeiro nome da pessao e vai usar integralmente o que estiver descrito nesta linha',
    target: 'Equipe de trabalho',
    keywords: 'equipe trabalho nome crachá crachás personalizar',
  },
  {
    question: 'Como cadastrar um cursista individual?',
    answer: 'Abra Cursista Individual para cadastrar, editar, consultar e imprimir a ficha de um cursista individual. Esse cadastro também pode ser realizado com link de cadastro.',
    target: 'Cursista Individual',
    keywords: 'cursista individual ficha inscrição inscricao cadastro editar consultar imprimir',
  },
  {
    question: 'Como cadastrar um casal de cursistas do EPC?',
    answer: 'Abra Cursista EPC para cadastrar, editar ou consultar a ficha do casal participante do EPC. Esse cadastro também pode ser realizado com link de cadastro.',
    target: 'Cursista EPC',
    keywords: 'cursista epc casal ficha inscrição inscricao cadastro editar consultar',
  },
  {
    question: 'Como cadastrar um casal de cursistas do SMP?',
    answer: 'Abra Cursista SMP para cadastrar, editar ou consultar a ficha do casal participante do SMP. Esse cadastro também pode ser realizado com link de cadastro.',
    target: 'Cursista SMP',
    keywords: 'cursista smp casal ficha inscrição inscricao cadastro editar consultar',
  },
  {
    question: 'Como usar o sistema para fazer uma sugestão de divisão de  cursistas em comunidades?',
    answer: 'Abra Comunidades, vá em distribuir casais/cursistas, lá voc~e encontra Fazer uma sugestão por idade. Clicando nessa opção, os casais com média de idade menores ficarão nas primeiras comuniadade e os mais velhos nas últimas. Como diz a opção, é apenas uma Sugestão. Feiot isso, clique em Exportar para comunidade e os casais serão alocados nas comuniadades.',
    target: 'Comunidades',
    keywords: 'comunidade comunidades lider líder monitor grupo organizar cursistas',
  },
   {
    question: 'Como criar uma nova comunidade?',
    answer: 'Abra Comunidades, clique em Incluir comunidade, aguarde alguns segundos e uma nova comunidade será criada após a última.',
    target: 'Comunidades',
    keywords: 'comunidade comunidades tracar mudar criar incluir alterar cursista cursistas',
  },
   {
    question: 'Como acrescentar cursistas em uma comunidade depois que as comunidades já estiverem formadas e com os cursistas adicionados?',
    answer: 'Abra Comunidades, clique em distribuir casais/cursista. Note que aparecerá cursista que ao lado do nomne vai estar escrito Sem comunidade. Clique em Sem comunidade, vai abrir uma janela com as opções de comunidades e ai é só selecionar a comunidade desejada. Feito isso, clique em Exportar para comunidade. Fazendo isso, o que já estava definido permanece e o que estava sem comunidade deve ser exibido na comunidade selecionada  ',
    target: 'Comunidades',
    keywords: 'comunidade comunidades inlcuir definir mudar exluir realocar',
  },
  {
    question: 'Como Excluir uma comunidade?',
    answer: 'Abra Comunidades, vá até comunidade que deseja exclir e clique em Excluir comunidade. Não se preocupe se hover cursistas na comunidade, eles não serão axcluidos porém terão que ser realocados em outras comunidades.',
    target: 'Comunidades',
    keywords: 'comunidade comunidades trocar mudar exluir realocar',
  },
   {
    question: 'Como trocar cursistas para outra comunidades?',
    answer: 'Abra Comunidades, vá até a comunidade onde está o cursista que será trocado, clicar em Mover para e selecionar na lista a comunidade de destino.',
    target: 'Comunidades',
    keywords: 'comunidade comunidades trocar mudar alterar cursista cursistas',
  },
     {
    question: 'Como cadastrar os tios e monitores em cada comunidade?',
    answer: 'Abra Comunidades, vá até a comunidade desejada, logo abaixo do nome da comunidade existe as opções Buscar tios da comunidade e Buscar monitores da comunidade. Esses tios e monitores deverão estar cadastrados na equipe de trabalho e setados nesta funcção',
    target: 'Comunidades',
    keywords: 'comunidade comunidades tio tios monitores monitor definir',
  },
   {
    question: 'Como separarar os cursistas em comunidades?',
    answer: 'Abra Comunidades, vá em distribuir casais/cursistas, lá voc~e encontra Fazer uma sugestão por idade. Clicando nessa opção, os casais com média de idade menores ficarão nas primeiras comuniadade e os mais velhos nas últimas. Como diz a opção, é apenas uma Sugestão. Feiot isso, clique em Exportar para comunidade e os casais serão alocados nas comuniadades.',
    target: 'Comunidades',
    keywords: 'comunidade comunidades lider líder monitor grupo organizar cursistas',
  },
   {
    question: 'Como imprimir crachás?',
    answer: 'Abra Crachás, clique em imprimir. Tem a opção Impressão por setor e Impressão por comunidade. Obs.: o modelo do crachá já deve ter sido definido na tela Definir crachás por setor/comunidade .',
    target: 'Crachás',
    keywords: 'cracha crachá crachas crachás imprimir impressão ',
  },
   {
    question: 'Como criar/personalizar crachás?',
    answer: 'Abra Crachás, clique em Configurar crachás. Dentro deste opção será possivel criar/personalizar/excluir crachás ',
    target: 'Crachás',
    keywords: 'cracha crachá personalizar criar incluir escolher definir imprimir impressão ',
  },
   {
    question: 'Como definir crachá por setor/comunidade?',
    answer: 'Abra Crachás, clique em Definir crachás por setor/comunidade. dentro desta tela será possivel definir o modelo de crachá que foi personalizado para cada serto/comunidade.',
    target: 'Crachás',
    keywords: 'cracha crachá escolher definir imprimir impressão ',
  },
   {
    question: 'Como excluir ou incluir um setor no retiro/quadrante?',
    answer: 'Essa opção não está disponível para o seu usuário, entrar em contato com o administrador do sistema para editar o retiro.',
    target: 'Quadrante',
    keywords: 'quadrante distribuição incluir setor',
  },
  {
    question: 'Como montar o quadrante?',
    answer: 'O quadrante já é preenchido automaticamente pelo cadastro de cursista e de equipe de trabalho.',
    target: 'Quadrante',
    keywords: 'quadrante distribuição distribuicao setor',
  },
  {
    question: 'Onde acompanho pagamentos recebidos?',
    answer: 'Abra Recebedor para acompanhar recebimentos, pagamentos e situações financeiras ligadas aos participantes.',
    target: 'Recebedor',
    keywords: 'recebedor pagamento pagar pago financeiro recebimento saldo caixa',
  },
  {
    question: 'Onde controlo as planilhas financeiras?',
    answer: 'Abra Financeiro para controlar planilhas, pagamentos, receitas, despesas, saldos e auditoria financeira.',
    target: 'Financeiro',
    keywords: 'financeiro planilha pagamento saldo despesa receita auditoria caixa',
  },
  {
    question: 'Como alterar minha senha?',
    answer: 'Abra Alterar senha para trocar a senha do usuário que está logado no sistema.',
    target: 'Alterar senha',
    keywords: 'senha trocar alterar login acesso usuario usuário',
  },
];

