export const helpArticles = [
  {
    question: 'Como vejo o resumo do retiro?',
    answer: 'Abra Início para ver os principais números do retiro em foco, atalhos de acompanhamento e indicadores gerais.',
    target: 'inicio',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral',
  },
    {
    question: 'Como encontro os cursistas aniversariantes do mês?',
    answer: 'Abra Início no menu principal, vá até a coluna Cursista, lá você encontra Aniversariantes do mês.',
    target: 'inicio',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pato formiga',
  },
  {
    question: 'Como copiar os links de cadastro?',
    answer: 'Abra Links de cadastro, confira o retiro em foco e copie o link correspondente à equipe, ao setor ou às fichas de cursistas.',
    target: 'retiros',
    keywords: 'link inscrição inscricao cadastro equipe cursista compartilhar enviar setor ficha',
  },
  {
    question: 'Como configurar ou publicar um retiro?',
    answer: 'Abra Configurações para criar, editar, publicar, encerrar ou revisar dados como datas, local, setores e opções do retiro.',
    target: 'configuracoes',
    keywords: 'configurar retiro criar editar publicar encerrar setores datas local',
  },
  {
    question: 'Como cadastrar alguém da equipe de trabalho?',
    answer: 'Abra Equipe de trabalho para cadastrar, editar ou consultar pessoas e fichas de adesão da equipe do retiro.',
    target: 'pessoas',
    keywords: 'equipe trabalho voluntario voluntário pessoa adesao adesão cadastrar editar consultar',
  },
  {
    question: 'Como conferir pendências nas inscrições?',
    answer: 'Abra Validação para revisar fichas, localizar inconsistências e conferir pendências antes do retiro.',
    target: 'validacao-inscricoes',
    keywords: 'validar validacao validação conferir pendencia pendência ficha inscrição inscricao',
  },
  {
    question: 'Como cadastrar um cursista individual?',
    answer: 'Abra Cursista Individual para cadastrar, editar, consultar e imprimir a ficha de um cursista individual.',
    target: 'cursista',
    keywords: 'cursista individual ficha inscrição inscricao cadastro editar consultar imprimir',
  },
  {
    question: 'Como cadastrar um casal de cursistas do EPC?',
    answer: 'Abra Cursista EPC para cadastrar, editar ou consultar a ficha do casal participante do EPC.',
    target: 'cursista-epc',
    keywords: 'cursista epc casal ficha inscrição inscricao cadastro editar consultar',
  },
  {
    question: 'Como cadastrar um casal de cursistas do SMP?',
    answer: 'Abra Cursista SMP para cadastrar, editar ou consultar a ficha do casal participante do SMP.',
    target: 'cursista-smp',
    keywords: 'cursista smp casal ficha inscrição inscricao cadastro editar consultar',
  },
  {
    question: 'Como organizar os cursistas em comunidades?',
    answer: 'Abra Comunidades para distribuir cursistas, definir líderes, monitores e acompanhar a organização dos grupos.',
    target: 'comunidades',
    keywords: 'comunidade comunidades lider líder monitor grupo organizar cursistas',
  },
  {
    question: 'Como preparar um recado para a equipe?',
    answer: 'Abra Recado à equipe para montar ou revisar o comunicado que será usado com a equipe do retiro.',
    target: 'recado-equipe',
    keywords: 'recado mensagem comunicado equipe aviso texto',
  },
  {
    question: 'Como imprimir os crachás?',
    answer: 'Abra Crachás, confira o retiro em foco, escolha o modelo desejado e use a opção de impressão disponível na tela.',
    target: 'crachas',
    keywords: 'cracha crachá crachas crachás imprimir impressão identificacao identificação etiqueta',
  },
  {
    question: 'Como montar o quadrante?',
    answer: 'Abra Quadrante para acompanhar e ajustar a distribuição dos participantes conforme a organização do retiro.',
    target: 'quadrante',
    keywords: 'quadrante distribuição distribuicao sala grupo organização organizacao',
  },
  {
    question: 'Onde acompanho pagamentos recebidos?',
    answer: 'Abra Recebedor para acompanhar recebimentos, pagamentos e situações financeiras ligadas aos participantes.',
    target: 'recebedor',
    keywords: 'recebedor pagamento pagar pago financeiro recebimento saldo caixa',
  },
  {
    question: 'Como gerar relatórios ou listagens?',
    answer: 'Abra Relatórios para gerar listagens, conferências e impressões administrativas do retiro.',
    target: 'relatorios',
    keywords: 'relatorio relatório relatorios relatórios listagem imprimir exportar conferir',
  },
  {
    question: 'Onde controlo as planilhas financeiras?',
    answer: 'Abra Financeiro para controlar planilhas, pagamentos, receitas, despesas, saldos e auditoria financeira.',
    target: 'financeiro',
    keywords: 'financeiro planilha pagamento saldo despesa receita auditoria caixa',
  },
  {
    question: 'Como alterar minha senha?',
    answer: 'Abra Alterar senha para trocar a senha do usuário que está logado no sistema.',
    target: 'alterar-senha',
    keywords: 'senha trocar alterar login acesso usuario usuário',
  },
  {
    question: 'Como fazer backup?',
    answer: 'Abra Backup e restauração para gerar backup ou restaurar dados quando houver autorização e cuidado prévio.',
    target: 'backup',
    keywords: 'backup restauração restauracao restaurar exportar importar segurança seguranca',
  },
  {
    question: 'Como criar ou editar usuários?',
    answer: 'Abra Usuários para gerenciar logins, perfis, permissões e acessos ao sistema.',
    target: 'usuarios',
    keywords: 'usuario usuário usuarios usuários permissao permissão permissoes permissões acesso login perfil',
  },
];
