export const helpArticles = [
  {
    question: 'Como vejo o resumo do retiro?',
    answer: 'Abra Início para ver os principais números do retiro em foco, atalhos de acompanhamento e indicadores gerais.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral',
  },
      {
    question: 'Onde encontrar o número de pessoas por dias no retiro?',
    answer: 'Abra Início, vá até a coluna Diversos, lá você encontra Presença por dia. A quantidade exibida jé é a soma da equipe de trabalho, cursistas e crianças no espaço kids inscritos no retiro no momento da consulta.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pessoas participação diária dias',
  },
      {
    question: 'Onde encontrar a relação das cidades com participação no retiro?',
    answer: 'Abra Início, vá até a coluna Diversos, lá você encontra Cidades participantes.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral cidade cidades presença',
  },
    {
    question: 'Onde encontrar os cursistas aniversariantes do mês?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Aniversariantes do mês.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pato formiga aniversariantes',
  },
      {
    question: 'Onde encontrar os cursistas com problemas de saúde?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Possui problemas de saúde.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral saúde',
  },
      {
    question: 'Onde encontrar os relação/resumo das quantidades de camisetas dos cursistas?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Camisetas dos cursistas.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral camisetas camiseta',
  },
      {
    question: 'Como imprimir a relação de tamanhos de camisetas por comunidade?',
    answer: 'Abra Comunidades, vá em Imprimir Nr camisetas por comunidade.',
    target: 'Comunidades',
    keywords: 'camiseta camisetas comunidade separar',
  },
      {
    question: 'Como encontrar os cursistas aniversariantes do mês?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra Aniversariantes do mês.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pato formiga aniversariantes',
  },
      {
    question: 'Onde encontrar os cursistas que necessitam de acolhimento?',
    answer: 'Abra Início, vá até a coluna Cursista, lá você encontra  Precisa acolhimento.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral acolhimento',
  },
      {
    question: 'Onde encontrar integrantes da equipe de trabalho  aniversariantes do mês?',
    answer: 'Abra Início, vá até a coluna Equipe de trabalho, lá você encontra Aniversariantes do mês.',
    target: 'Início',
    keywords: 'home painel resumo indicadores estatisticas começo andamento visão geral pato formiga aniversariantes',
  },
      {
    question: 'Onde encontrar os integrantes da equipe de trabalho que solicitaram quandrante impresso?',
    answer: 'Abra Início, vá até a coluna Equipe de trabalho, lá você encontra a informação Quadrante(s) impresso.',
    target: 'Início',
    keywords: 'quadrante',
  },
      {
    question: 'Como calcular quantos quadrantes deve ser impresso?',
    answer: 'Verifique a quantidade de cursistas ou de casais cursistas e acrescente á quantidade solicitada pela equipe de trabalho.',
    target: 'Início',
    keywords: 'quantidade quadrante',
  },
      {
    question: 'Como imprimir/visualizar o quadrante?',
    answer: 'Abra Quadrante, lá você encontra a opçãso Imprimir relatório completo.',
    target: 'Quadrante',
    keywords: 'quadrante relatório',
  },
        {
    question: 'Como imprimir/visualizar lista para amigo secreto?',
    answer: 'Abra Quadrante, lá você encontra a opção Imprimir relatório para amigo secreto.',
    target: 'Quadrante',
    keywords: 'amigo secreto',
  },
    {
    question: 'Como compartilhar os links de inscrição das equipes de trabalho?',
    answer: 'Abra Links de cadastro e digite no campo Buscar setor ativo qual setor que deseja compartilhar o link. Observe que em cada setor há dois links. CADASTRO que é para cadastro da equipe de trabalho daquele setor especificamente e deve ser encaminhado para quem vai preencher a inscrição. ACOMPANHAMENTO DO LIDER que serve para o coordenador do setor verificar quem já efetuou a inscrição, esse último link fica apenas com o coordenador do setor.',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro equipe trabalho compartilhar enviar setor',
  },
      {
    question: 'Como compartilhar os links de inscrição de fichas de cursistas?',
    answer: 'Abra Links de cadastro, digite no campo Buscar ficha, qual a ficha que deseja compartilhar o link. Abrirá uma lista que será possivel visualizar quais fichas já estão cadastradas. Busque uma ficha que estiver livre e clique nela. Você encontrará o link para compartilhamento daquela ficha especificamente. Opcionalmente você poderá preencher o campo Enviado para que serve como campo de observação ficando registrado para quem foi enviado o link. Lembrando que esse campo de observação só ficará quardado se cliar em Salvar',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cursista compartilhar enviar',
  },
      {
    question: 'Como cancelar links de isncrição de cursistas?',
    answer: 'Abra Links de cadastro e digite no campo Buscar ficha qual link deseja cancelar. Ficará visível a opção INSCRIÇÃO ENCERRADA, clique nela, aguarde alguns segundos e pronto, o link ficará inválido. Obs.: Essa operação poderá ser revertida clicando novamente nessa opção',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cancelar reverter compartilhar enviar',
  },
      {
    question: 'Posso cadastrar pelo sistema uma ficha de cursista de um link que foi compartilhado?',
    answer: 'Pode porém lembrando que o link compartilhado daquele número de ficha especificamente ficará inválido a partir do salvamento da ficha do cursista',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cancelar reverter compartilhar enviar cursista sistema logado',
  },
      {
    question: 'Como encerrar as inscrições da equipe de trabalho?',
    answer: 'Abra Links de cadastro e digite no campo Buscar setor ativo o setor que deseja, clique no setor e ficará visivel a opção Inscrições encerradas. Obs.: Essa ação pode ser revertida apenas clicando novamente nessa mesma opção.',
    target: 'Links de cadastro',
    keywords: 'link inscrição inscricao cadastro cancelar reverter compartilhar enviar equipe trabalho',
  },
  {
    question: 'Como configurar ou publicar um retiro?',
    answer: 'Abra Configurações para criar, editar, publicar, encerrar ou revisar dados como datas, local, setores e opções do retiro.',
    target: 'Configurações',
    keywords: 'configurar retiro criar editar publicar encerrar setores datas local',
  },
  {
    question: 'Como cadastrar alguém da equipe de trabalho?',
    answer: 'Abra Equipe de trabalho para cadastrar, editar ou consultar pessoas e fichas de adesão da equipe do retiro.',
    target: 'Equipe de trabalho',
    keywords: 'equipe trabalho voluntario voluntário pessoa adesao adesão cadastrar editar consultar',
  },
  {
    question: 'Como conferir pendências nas inscrições?',
    answer: 'Abra Validação para revisar fichas, localizar inconsistências e conferir pendências antes do retiro.',
    target: 'Validação',
    keywords: 'validar validacao validação conferir pendencia pendência ficha inscrição inscricao',
  },
  {
    question: 'Como cadastrar um cursista individual?',
    answer: 'Abra Cursista Individual para cadastrar, editar, consultar e imprimir a ficha de um cursista individual.',
    target: 'Cursista Individual',
    keywords: 'cursista individual ficha inscrição inscricao cadastro editar consultar imprimir',
  },
  {
    question: 'Como cadastrar um casal de cursistas do EPC?',
    answer: 'Abra Cursista EPC para cadastrar, editar ou consultar a ficha do casal participante do EPC.',
    target: 'Cursista EPC',
    keywords: 'cursista epc casal ficha inscrição inscricao cadastro editar consultar',
  },
  {
    question: 'Como cadastrar um casal de cursistas do SMP?',
    answer: 'Abra Cursista SMP para cadastrar, editar ou consultar a ficha do casal participante do SMP.',
    target: 'Cursista SMP',
    keywords: 'cursista smp casal ficha inscrição inscricao cadastro editar consultar',
  },
  {
    question: 'Como organizar os cursistas em comunidades?',
    answer: 'Abra Comunidades para distribuir cursistas, definir líderes, monitores e acompanhar a organização dos grupos.',
    target: 'Comunidades',
    keywords: 'comunidade comunidades lider líder monitor grupo organizar cursistas',
  },
  {
    question: 'Como preparar um recado para a equipe?',
    answer: 'Abra Recado à equipe para montar ou revisar o comunicado que será usado com a equipe do retiro.',
    target: 'Recado à equipe',
    keywords: 'recado mensagem comunicado equipe aviso texto',
  },
  {
    question: 'Como imprimir os crachás?',
    answer: 'Abra Crachás, confira o retiro em foco, escolha o modelo desejado e use a opção de impressão disponível na tela.',
    target: 'Crachás',
    keywords: 'cracha crachá crachas crachás imprimir impressão identificacao identificação etiqueta',
  },
  {
    question: 'Como montar o quadrante?',
    answer: 'Abra Quadrante para acompanhar e ajustar a distribuição dos participantes conforme a organização do retiro.',
    target: 'Quadrante',
    keywords: 'quadrante distribuição distribuicao sala grupo organização organizacao',
  },
  {
    question: 'Onde acompanho pagamentos recebidos?',
    answer: 'Abra Recebedor para acompanhar recebimentos, pagamentos e situações financeiras ligadas aos participantes.',
    target: 'Recebedor',
    keywords: 'recebedor pagamento pagar pago financeiro recebimento saldo caixa',
  },
  {
    question: 'Como gerar relatórios ou listagens?',
    answer: 'Abra Relatórios para gerar listagens, conferências e impressões administrativas do retiro.',
    target: 'Relatórios',
    keywords: 'relatorio relatório relatorios relatórios listagem imprimir exportar conferir',
  },
  {
    question: 'Onde controlo as planilhas financeiras?',
    answer: 'Abra Financeiro para controlar planilhas, pagamentos, receitas, despesas, saldos e auditoria financeira.',
    target: 'Financeiro',
    keywords: 'financeiro planilha pagamento saldo despesa receita auditoria caixa',
  },
  {
    question: 'Como alterar minha senha?',
    answer: 'Abra Alterar senha para trocar a senha do usuário que está logado no sistema.',
    target: 'Alterar senha',
    keywords: 'senha trocar alterar login acesso usuario usuário',
  },
  {
    question: 'Como fazer backup?',
    answer: 'Abra Backup e restauração para gerar backup ou restaurar dados quando houver autorização e cuidado prévio.',
    target: 'Backup e restauração',
    keywords: 'backup restauração restauracao restaurar exportar importar segurança seguranca',
  },
  {
    question: 'Como criar ou editar usuários?',
    answer: 'Abra Usuários para gerenciar logins, perfis, permissões e acessos ao sistema.',
    target: 'Usuários',
    keywords: 'usuario usuário usuarios usuários permissao permissão permissoes permissões acesso login perfil',
  },
];

